name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do repositorio
      uses: actions/checkout@v4.1.0
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PWD }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: |
          niltonpita/comments_api:${{ github.run_number }}
          niltonpita/comments_api:latest
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: Checkout do repositorio
      uses: actions/checkout@v4.1.0
    - name: Configuração da credencial da AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        aws-region: us-east-1
    - name: Configurar o KubeConfig
      shell: bash
      run: |
         kubectl apply -f deploy_nt.yaml --validate=false
    - name: Deploy to Kubernetes cluster
      uses: Azure/k8s-deploy@v4.9
      with:
        manifests:
        images: |
          niltonpita/comments_api:latest